# -*- coding: utf-8 -*-
"""asm3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qPF8fimVCMD_w584Y771GLzSqXDReY-6
"""

import pandas as pd
df=pd.read_csv("TESLA Search Trend vs Price.csv")
df1=pd.read_csv("Bitcoin Search Trend.csv")
df2=pd.read_csv("Daily Bitcoin Price.csv")
df3=pd.read_csv("UE Benefits Search vs UE Rate 2004-19.csv")

df.head(5)

df1.head(5)

df2.head(5)

df3.head(5)

df.tail(5)

df1.tail(5)

df2.tail(5)

df3.tail(5)

df.describe()

df1.describe()

df2.describe()

df3.describe()

df.dropna(inplace=True)

df1.dropna(inplace=True)

df2.dropna(inplace=True)

df3.dropna(inplace=True)

#mice=Multiple imputation by chain equations(used to handle missing data)

df.MONTH=pd.to_datetime(df.MONTH)

df1.MONTH=pd.to_datetime(df1.MONTH)

df2.DATE=pd.to_datetime(df2.DATE)

df3.MONTH=pd.to_datetime(df3.MONTH)

df2_monthly=df2.resample('M',on='DATE').mean()

df_monthly=df.resample('M',on='MONTH').mean()

df2_monthly

df2

import matplotlib.pyplot as plt
ax1=plt.gca()
ax2=ax1.twinx()
ax1.set_ylabel('Tesla Stockprice')
ax2.set_ylabel('Search Trend')
ax1.plot(df.MONTH,df.TSLA_USD_CLOSE,color='red')
ax2.plot(df.MONTH,df.TSLA_WEB_SEARCH)

