# -*- coding: utf-8 -*-
"""colab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UUGCngStyzq1i-lD4sSONRpxA_j1hjU7
"""

import pandas as pd

df=pd.read_csv("salaries_by_college_major.csv")
df

df.columns

df.isnull()

clean_df=df.dropna()
clean_df
#there are several procedures to handle missing data. one of them is PMM(Predictive Mean Matching)

clean_df['Starting Median Salary']

clean_df['Starting Median Salary'].max()

clean_df['Starting Median Salary'].idxmax()

clean_df.loc[43]

clean_df['Undergraduate Major'][43]

#What college major has the highest mid-career salary?How much do graduates with this major earn
#Which college major has the lowest starting salary and how much do graduates earn after university?

clean_df['Mid-Career Median Salary'].idxmax()

clean_df.loc[8]

clean_df['Mid-Career Median Salary'].idxmin()

clean_df.loc[18]

#ans1: a chemical engineering graduate has the highest mid career salary of Rs.107000
#ans2: a education graduate has the lowest starting career salary of Rs.34900

newcol=clean_df['Mid-Career 90th Percentile Salary']-clean_df['Mid-Career 10th Percentile Salary']
newcol

clean_df.drop('Risk Factor',axis=1)

clean_df.insert(6,'Risk Factor',newcol)

clean_df

clean_df.sort_values('Risk Factor')

clean_df.groupby('Group').count()

clean_df.groupby('Group').mean()