# -*- coding: utf-8 -*-
"""pca1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e--XRM5OnAgaFplWbCYjkGZKhOdsYX4E
"""

import pandas as pd

data=pd.read_csv("dataset_pca2 - Sheet1.csv")

data

data['age'].describe()

data['income'].describe()

data.loc[data['income']>60000] #filtering rows of the dataframe where income>60000

data.MONTH=pd.to_datetime(data.MONTH) #converting 'MONTH' column of the dataframe into DateTime format

data.MONTH

data.loc[data['age']>40].count()
#28 people are older than 40

data.groupby('race').mean()

import matplotlib.pyplot as plt

plt.title("line chart")
plt.xlabel('date')
plt.ylabel('Income')
plt.plot(data.MONTH,data.income)
plt.show()

data1= [
    {"datetime": "2022-01-01", "Name": "John", "age": 25, "income": 50000, "race": "White"},
    {"datetime": "2022-01-02", "Name": "Alice", "age": 30, "income": 60000, "race": "Asian"},
    {"datetime": "2022-01-03", "Name": "Bob", "age": 35, "income": 75000, "race": "Black"}
      ]

s=0
for i in range(0,len(data1)):
    s=s+data1[i]["age"]
mean=s/3
print(mean) #average age in the dataset

s1=0
for j in range(0,len(data1)):
    s1=s1+data1[j]["income"]
mean1=s1/3
print(mean1) #average income in the dataset

c=0
for j in range(0,len(data1)):
  if data1[i]["age"]>30:
    c+=1
    print(f"{c} person is older than 30")
    break
  else:
    c+=0
    print("no persons are older than 30")
    break

import math
def func(a,b,c):
  product=a*b*c
  print(product)
  s1=math.sin(a)
  s2=math.sin(b)
  s3=math.sin(c)
  c1=math.cos(a)
  c2=math.cos(b)
  c3=math.cos(c)
  l1=math.log(a, 10)
  l2=math.log(b, 10)
  l3=math.log(c, 10)
  print(s1)
  print(s2)
  print(s3)
  print(c1)
  print(c2)
  print(c3)
  print(l1)
  print(l2)
  print(l3)
a=int(input("obs1:"))
b=int(input("obs2:"))
c=int(input("obs3:"))
func(a,b,c)

3